### ISSUE TITLE
Period multiplicator as part of the Proof's configuration

### ISSUE THREAD

**Issue by AuHau** [codex-storage/codex-contracts-eth#108]
https://github.com/codex-storage/codex-contracts-eth/blob/master/contracts/Proofs.sol#L48

The Period multiplicator (67) in `getPointer()` function should be configurable as it is coupled with the downtime parameter.

We should also better understand what configuration values we will use in real deployment, because then maybe we would not even need the multiplication? I would assume that the Period should be quite long, but Mark pointed out that it should not be longer than the 256 blocks window.

**Comment by emizzle** [comment]
If I understand this correctly (which is questionable 😂 ), then I don't understand why a Period can't be longer than 256 blocks. The *pointer* should never be greater than 255, otherwise we wouldn't be able to get a block hash for the challenge entropy in `getChallenge` (see below). However, the `_getPointer` calculation uses `% 256`, so the pointer would never be greater than 255. But the period, if longer than 256, would continue to wrap and be going in and out of downtime.
```solidity
function _getPointer(SlotId id, Period period) internal view returns (uint8) {
    uint256 blockNumber = block.number % 256;
    // To ensure the pointer does not remain in downtime for many consecutive
    // periods, for each period increase, move the pointer 67 blocks. We've
    // chosen a prime number to ensure that we don't get cycles.
    uint256 periodNumber = (Period.unwrap(period) * 67) % 256;
    uint256 idOffset = uint256(SlotId.unwrap(id)) % 256;
    uint256 pointer = (blockNumber + periodNumber + idOffset) % 256;
    return uint8(pointer);
  }

function _getChallenge(uint8 pointer) internal view returns (bytes32) {
    bytes32 hash = blockhash(block.number - 1 - pointer);
    assert(uint256(hash) != 0);
    return keccak256(abi.encode(hash));
  }
```
