### ISSUE TITLE
Add Codex Testnet network

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/codex-contracts-eth#112]
As we discussed, we  should introduce `testnet` for Codex Testnet and that require some modificaitons
 - Add new network to the [`hardhat.config.js`](https://github.com/codex-storage/codex-contracts-eth/blob/master/hardhat.config.js)
 - Add new network to the [`verifier/networks`](https://github.com/codex-storage/codex-contracts-eth/tree/master/verifier/networks)

We discussed the name `testnet`, but shouldn't `codex_testnet` be more appropriate similar to `taiko_test`?

Part of https://github.com/codex-storage/infra-codex/issues/186

**Comment by emizzle** [comment]
> shouldn't codex_testnet be more appropriate similar to taiko_test?

Since `taiko_test` deployed to the Taiko L2 network, it makes sense for it to be named as such. In our case, the network is our own test Ethereum network, so we could name it something, as is typical for these types of testnets, eg `rinkeby` is one of Ethereum's testnets. Have [asked the team](https://discord.com/channels/895609329053474826/1230457525854539819/1246981358849359983) what they think regarding suitable names.
